spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/customer
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
      